---
# tasks file for aws-create-elb

- name: Create an ELB and attach target group
  elb_application_lb:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    name: "{{ elb_name }}"
    state: present
    region: "{{ region }}"
    security_groups: 
      - "{{ security_group }}"
     #vpc_id: "{{ vpc_id }}"
    subnets:
      - "{{ subnet1 }}"
      - "{{ subnet2 }}"
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupName: "{{ elb_target_group }}"
  register: elbcreated

- name: Collect ELB Public DNS
  set_fact:
    elb_public_dns: "{{ elbcreated.dns_name }}"

- name: ELB Public DNS 
  debug:
    msg: "{{ elb_public_dns }}"
   
