---
# tasks file for aws-delete-elb
- name: Delete ELB
  elb_application_lb:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    region: "{{ region }}"
    name: "{{ elb_name }}"
    state: absent
    wait: yes
