---
- name: Install httpd
  hosts: nodes
  become: true
  gather_facts: false
  vars:
    ansible_user: ssm-user
    ansible_aws_ssm_profile: devops
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: ansible-demo-bucket-2022apr07
    ansible_aws_ssm_region: ap-southeast-1
  tasks:
    - name: Install httpd
      yum: 
        name: httpd
        state: present