---
# tasks file for aws-get-vpc-id
- name: Get VPC Details
  amazon.aws.ec2_vpc_net_info:
    profile: "{{ aws_boto_profile }}"
    region: "{{ aws_region }}"
  register: aws_vpc_details
  #  filters:
  #    "tag:Name": Example

- name: Collect VPC ID
  set_fact:
    aws_vpc_id: "{{ aws_vpc_details.vpcs[0].vpc_id }}"