#- name: Add newly created ec2 instance to a host group
#  add_host:
#    name: "{{ item.instances[0].public_ip }}"
#    groups: "{{ inventory_webgroup }}"
#    #ansible_ssh_private_key_file: "{{ aws_key_pem }}"

- name: Register instance target to a target group
  elb_target:
    #aws_access_key: "{{ec2_access_key}}"
    #aws_secret_key: "{{ec2_secret_key}}"
    profile: "{{ aws_boto_profile }}"
    target_group_name: "{{ aws_elb_target_group }}"
    target_id: "{{ item.instances[0].id }}"
    region: "{{ region }}"
    state: present

- name: Collect newly created ec2 in a list
  set_fact:
    new_ec2_list: "{{ new_ec2_list }} + [ '{{ item.instances[0].public_ip }}' ]"
    aws_ec2_created: True