---
roles:
  # Install a role from Ansible Galaxy.
  #- name: geerlingguy.java
  #  version: 1.9.6

collections:

  - name: paloaltonetworks.panos
    version: 2.9.0
  
  - name: check_point.mgmt
    version: 3.0.0
    