---
- name: List to String Conversion
  hosts: localhost
  vars:
    my_list:
      - "apple"
      - "mango"
      - "orange"
  tasks:
    - name: Print the List
      debug:
        msg: "{{ my_list }}"

    - name: Concatenate a list to string
      set_fact:
        my_string: "{{ my_list | join(',') }}"

    - name: Print the String
      debug:
        msg: "{{ my_string }}"

    - name: "New Task Added"
      ansible.builtin.debug:
        msg: "This is a new task added for demo"

    - name: Print the List
      debug:
        msg: "{{ workflow_url }}, {{ tower_job_id }}"    
    # - name: "Pause for testing"
    #   ansible.builtin.pause:
    #     minutes: 5