---
# tasks file for aws-delete-ec2

- name: Collect Instance infromation by tag, subnet and type
  ec2_instance_facts:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ item.value.name }}"
      network-interface.subnet-id: "{{ item.value.vpc_subnet_id }}"
      instance-type: "{{ item.value.instance_type }}"
  loop: "{{ lookup('dict', ec2_new_list, wantlist=True) }}"
  register: ec2_collection

- name: Terminate ec2 instances
  ignore_errors: True
  ec2:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    region: "{{ region }}"
    state: absent
    instance_ids: "{{ item }}"  
  loop: "{{ ec2_collection | json_query('results[*].instances[*].instance_id') }}"
  register: deleted_ec2

#- name: "Deleted ec2"
#  debug:
#    msg: "{{ deleted_ec2 }}"
